title : Retrospect
description: 'Retrospect'

markdown: kramdown
highlighter: rouge
logo: false
g-analytics: UA-141365392-1

 # paging
plugins: [jekyll-paginate]
paginate: 3
paginate_path: “/blog/page:num/”
baseurl: /
#plugins: [jekyll-gist]
permalink: /:year/:month/:title.html
